name: Build

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build and test
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]
        composer-flags: [ "" ]
        experimental: [ false ]
        include:
          - php: 7.2
            composer-flags: "--prefer-lowest"
          - php: "8.4" # TODO move that to a normal job once phpspec supports PHP 8.4
            composer-flags: "--ignore-platform-req=php+"
          - php: nightly
            composer-flags: "--ignore-platform-req=php+"
            experimental: true

    steps:
      -   uses: actions/checkout@v4

      -   name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "${{ matrix.php }}"
            coverage: none

      -   name: Install dependencies
          run: COMPOSER_ROOT_VERSION=dev-master composer update ${{ matrix.composer-flags }}
          id: end-of-setup

      -   name: Run tests (phpspec)
          run: ./vendor/bin/phpspec run --format=dot
          if: always() && steps.end-of-setup.outcome == 'success'

      -   name: Run tests (phpunit)
          run: ./vendor/bin/phpunit
          if: always() && steps.end-of-setup.outcome == 'success'

  phpstan:
    runs-on: ubuntu-latest
    name: Static analysis
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
      - name: Install dependencies
        run: COMPOSER_ROOT_VERSION=dev-master composer update
      - run: ./vendor/bin/phpstan

  coding-standards:
    runs-on: ubuntu-latest
    name: Coding standards
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
      - name: Install PHP-CS-Fixer
        run: COMPOSER_ROOT_VERSION=dev-master composer require php-cs-fixer/shim
      - run: ./vendor/bin/php-cs-fixer check --verbose --diff
